sudo: required
services:
  - docker

berore_install:
  - docker build -f ./client/Dockerfile.dev -t ndonova/complex ./client
scripts:
  - docker run ndonova/complex npm run test -- --coverage
after_success:
  - docker build -t ndonova/milti-client ./client
  - docker build -t ndonova/milti-web ./web
  - docker build -t ndonova/milti-server ./server
  - docker build -t ndonova/milti-worker ./worker

deploy:
  provider: elasticbeanstalk
  region: "take it in link for examle: Docker-env.wertyukjhv.us-west-2.elasticbeanstalk.com it will be us-west-2"
  app: "name app in elasticbeanstalk"
  env: "Docker-env"
  bucket_name: "Go to menu Services > S3 and find the name elasticbeanstalk-us-west-2-547765764343"
  bucket_path: "equal app name in this file"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"